package back;
public enum LogrosTitle {
    ENCUENTROS_CERCANOS_DEL_TERCER_TIPO,
    FELIZ_ANIVERSARIO,
    CUANDO_LLEGA,
    UNA_MUY_VIEJA_CONOCIDA,
    A_TRABAJAR,NO_ME_DEJAN_SALIR,
    BIENVENIDOS_AL_ABISMO_DE_LOS_LAMENTOS,
    CHIN_CHON_CHIN,
    ALGUNAS_COSAS,
    IM_THE_ONE_WHO_KNOCKS
}
